### PR TITLE
Pull request on apple.com's webpage

### PR DESCRIPTION
**Pull request by Datagirlcmr**
Solo Project on cloning apple.com's old webpage

### CODE REVIEW

**Comment by ebukaume** [comment]
## Changes Required! :stop_sign: 

Hi @Datagirlcmr :wave: 

Kudos on your efforts so far. You are doing great. However, there is something wrong with your page. Why are those images aligned to the left of the page?

review-apple-distorted
**Read [this article](https://css-tricks.com/almanac/properties/b/background-position/) to help you understand how to position your backgroud images properly**

Also, why did you choose to go with this particular gradient values? It doesn't come close to the one on the original page. _You may want to inspect the original one using the `Developer tool` on your browser._

**Please submit another code review request after fixing the issues.**

Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Comment by Datagirlcmr** [comment]
Thanks for the prompt feedback. The image performs well on my browser so I
don't understand what to fix.

The gradient on the original site was an image so the developper tools
could not help that. I tried to recreate it instead of just using the image.




*Kind Regards*
*DATAGIRLSOFTWARE ENGINEER, WEB DESIGN & APPLICATIONS*
*MOBILE *: +237 677 30 30 86

                +234 9024840152

**Comment by ebukaume** [comment]
I guess raw.githack.com cached the older version. 

review-apple-new

**Now, let's handle these issues:**
review-apple-new

- [ ] Can you see those margin around the body? Get rid of it so the background wraps well.
review-apple-margin
**It appears it has a margin of 8px. Consider doing a reset of the defaults first.**

- [ ] The 4 product images are supposed to be links.
review-apple-products

- [ ] Finally, can you make the last element in the navbar to be of the same size as others?
review-apple-navbar-2

**Please submit another code review request after making those changes.**


Happy Coding :v: 
**Ebuka Umeokonkwo**
 [Github](https://github.com/ebukaume) | [Linkedin](https://www.linkedin.com/in/ebukaume) | [Slack](https://app.slack.com/team/UFDKXE68L) | [Twitter](https://twitter.com/ebukaume)

**Review by suretrust — APPROVED** [review]
### Great job! Let's get this merged! :tada: 

_Good luck with your future projects and happy coding!_

**Pull request merged**
